name: Daily YouTube Short

on:
  schedule:
    - cron: '0 13 * * *'   # Runs every day at 13:00 UTC => 18:30 IST
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install moviepy gTTS pillow google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client


      - name: Run script
        env:
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
        run: python generate_and_upload_short.py
